public with sharing class calculator {
    public calculator() {
    }
        public static void substraction(Integer a, Integer b)
        {
            Intgit eger c=a-b;
        }
        public static void addition(Integer a, Integer b)
        {
            Integer c=a+b;
        }

        public static void division(Integer n, Integer m)
        {
            Integer o=m/n;
        }
        public static void evennumber(Integer n, Integer m)
        {
            Integer o=m/2;
        }
    }

             public static void multiply(Integer a, Integer b)
     {
         Integer c=a*b;
     }
}

